# Generated by Django 4.0.4 on 2022-10-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_category_assignment_category_course_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
